[webserver]
port = 9595

[logging]
level = 5 #Debug

[database]
username = "root"
password = "uma@1992"
dbname = "shoppinglist"
ip = "mysql"
port = 3306
max_connection_attempt = 60

[kv]
ip = "redis"
#ip = "127.0.0.1:9675"